/**
 * This file is part of the TA Buddy project.
 * Copyright (c) 2014 Alexey Aksenov ezh@ezh.msk.ru
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Global License version 3
 * as published by the Free Software Foundation with the addition of the
 * following permission added to Section 15 as permitted in Section 7(a):
 * FOR ANY PART OF THE COVERED WORK IN WHICH THE COPYRIGHT IS OWNED
 * BY Limited Liability Company «MEZHGALAKTICHESKIJ TORGOVYJ ALIANS»,
 * Limited Liability Company «MEZHGALAKTICHESKIJ TORGOVYJ ALIANS» DISCLAIMS
 * THE WARRANTY OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Global License for more details.
 * You should have received a copy of the GNU Affero General Global License
 * along with this program; if not, see http://www.gnu.org/licenses or write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA, 02110-1301 USA, or download the license from the following URL:
 * http://www.gnu.org/licenses/agpl.html
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Global License.
 *
 * In accordance with Section 7(b) of the GNU Affero General Global License,
 * you must retain the producer line in every report, form or document
 * that is created or manipulated using TA Buddy.
 *
 * You can be released from the requirements of the license by purchasing
 * a commercial license. Buying such a license is mandatory as soon as you
 * develop commercial activities involving the TA Buddy software without
 * disclosing the source code of your own applications.
 * These activities include: offering paid services to customers,
 * serving files in a web or/and network application,
 * shipping TA Buddy with a closed source product.
 *
 * For more information, please contact Digimead Team at this
 * address: ezh@ezh.msk.ru
 */

package org.digimead.tabuddy.desktop.core.ui.view.defaultv;

import org.digimead.tabuddy.desktop.core.ui.ResourceManager;
import org.eclipse.swt.SWT;
import org.eclipse.swt.layout.FillLayout;
import org.eclipse.swt.layout.FormAttachment;
import org.eclipse.swt.layout.FormData;
import org.eclipse.swt.layout.FormLayout;
import org.eclipse.swt.layout.GridData;
import org.eclipse.swt.layout.GridLayout;
import org.eclipse.swt.widgets.Composite;

/**
 * This file is autogenerated by Google WindowBuilder Pro
 *
 * @author ezh
 */
public class ContentSkel extends Composite {
	private Composite compositeAbout;
	private Composite compositeInfo;
	private Composite compositeQuotation;
	private Composite compositeTitle;

	/**
	 * Create the composite.
	 *
	 * @param parent
	 * @param style
	 */
	public ContentSkel(Composite parent, int style) {
		super(parent, style);
		setLayout(new GridLayout(1, false));

		Composite compositeMain = new Composite(this, SWT.BORDER);
		GridData gd_compositeMain = new GridData(SWT.FILL, SWT.FILL, true, true, 1, 1);
		gd_compositeMain.minimumWidth = 300;
		gd_compositeMain.minimumHeight = 300;
		compositeMain.setLayoutData(gd_compositeMain);
		compositeMain.setBackground(ResourceManager.getColor(SWT.COLOR_WHITE));
		compositeMain.setLayout(new FormLayout());

		compositeTitle = new Composite(compositeMain, SWT.NONE);
		compositeTitle.setBackground(ResourceManager.getColor(SWT.COLOR_WHITE));
		compositeTitle.setLayout(new GridLayout(1, false));
		FormData fd_compositeTitle = new FormData();
		fd_compositeTitle.left = new FormAttachment(0);
		fd_compositeTitle.right = new FormAttachment(100);
		fd_compositeTitle.bottom = new FormAttachment(50);
		compositeTitle.setLayoutData(fd_compositeTitle);

		compositeQuotation = new Composite(compositeMain, SWT.NONE);
		compositeQuotation.setBackground(ResourceManager.getColor(SWT.COLOR_WHITE));
		compositeQuotation.setLayout(new FillLayout(SWT.HORIZONTAL));
		FormData fd_compositeQuotation = new FormData();
		fd_compositeQuotation.height = 16;
		fd_compositeQuotation.right = new FormAttachment(70);
		fd_compositeQuotation.left = new FormAttachment(20);
		fd_compositeQuotation.top = new FormAttachment(compositeTitle);
		compositeQuotation.setLayoutData(fd_compositeQuotation);

		compositeInfo = new Composite(compositeMain, SWT.NONE);
		compositeInfo.setBackground(ResourceManager.getColor(SWT.COLOR_WHITE));
		FormData fd_compositeInfo = new FormData();
		fd_compositeInfo.right = new FormAttachment(90);
		compositeInfo.setLayoutData(fd_compositeInfo);
		compositeInfo.setLayout(new GridLayout(2, false));
		fd_compositeInfo.bottom = new FormAttachment(compositeAbout);

		compositeAbout = new Composite(compositeMain, SWT.NONE);
		compositeAbout.setBackground(ResourceManager.getColor(SWT.COLOR_WHITE));
		FormData fd_compositeAbout = new FormData();
		fd_compositeAbout.bottom = new FormAttachment(100);
		compositeAbout.setLayoutData(fd_compositeAbout);
		compositeAbout.setLayout(new FillLayout(SWT.HORIZONTAL));
	}

	@Override
	protected void checkSubclass() {
		// Disable the check that prevents subclassing of SWT components
	}

	protected Composite getCompositeAbout() {
		return compositeAbout;
	}

	protected Composite getCompositeInfo() {
		return compositeInfo;
	}

	protected Composite getCompositeQuotation() {
		return compositeQuotation;
	}

	protected Composite getCompositeTitle() {
		return compositeTitle;
	}
}
