/**
 * This file is part of the TA Buddy project.
 * Copyright (c) 2014 Alexey Aksenov ezh@ezh.msk.ru
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Global License version 3
 * as published by the Free Software Foundation with the addition of the
 * following permission added to Section 15 as permitted in Section 7(a):
 * FOR ANY PART OF THE COVERED WORK IN WHICH THE COPYRIGHT IS OWNED
 * BY Limited Liability Company «MEZHGALAKTICHESKIJ TORGOVYJ ALIANS»,
 * Limited Liability Company «MEZHGALAKTICHESKIJ TORGOVYJ ALIANS» DISCLAIMS
 * THE WARRANTY OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Global License for more details.
 * You should have received a copy of the GNU Affero General Global License
 * along with this program; if not, see http://www.gnu.org/licenses or write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA, 02110-1301 USA, or download the license from the following URL:
 * http://www.gnu.org/licenses/agpl.html
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Global License.
 *
 * In accordance with Section 7(b) of the GNU Affero General Global License,
 * you must retain the producer line in every report, form or document
 * that is created or manipulated using TA Buddy.
 *
 * You can be released from the requirements of the license by purchasing
 * a commercial license. Buying such a license is mandatory as soon as you
 * develop commercial activities involving the TA Buddy software without
 * disclosing the source code of your own applications.
 * These activities include: offering paid services to customers,
 * serving files in a web or/and network application,
 * shipping TA Buddy with a closed source product.
 *
 * For more information, please contact Digimead Team at this
 * address: ezh@ezh.msk.ru
 */

package org.digimead.tabuddy.desktop.core.ui.view.defaultv;

import org.digimead.tabuddy.desktop.core.ui.ResourceManager;
import org.eclipse.swt.SWT;
import org.eclipse.swt.layout.FormAttachment;
import org.eclipse.swt.layout.FormData;
import org.eclipse.swt.layout.FormLayout;
import org.eclipse.swt.layout.GridData;
import org.eclipse.swt.layout.GridLayout;
import org.eclipse.swt.widgets.Composite;

/**
 * This file is autogenerated by Google WindowBuilder Pro
 *
 * @author ezh
 */
public class ContentSkel extends Composite {
	private Composite compositeAbout;
	private Composite compositeInfo;
	private Composite compositeMonitor1;
	private Composite compositeMonitor2;
	private Composite compositeTitle;

	/**
	 * Create the composite.
	 *
	 * @param parent
	 * @param style
	 */
	public ContentSkel(Composite parent, int style) {
		super(parent, style);
		setLayout(new FormLayout());

		Composite compositeMain = new Composite(this, SWT.NONE);
		compositeMain.setBackground(ResourceManager.getColor(SWT.COLOR_WHITE));
		FormData fd_compositeMain = new FormData();
		fd_compositeMain.bottom = new FormAttachment(100, 0);
		fd_compositeMain.top = new FormAttachment(0, 0);
		fd_compositeMain.left = new FormAttachment(0, 0);
		fd_compositeMain.right = new FormAttachment(100, 0);
		compositeMain.setLayoutData(fd_compositeMain);
		compositeMain.setLayout(new GridLayout(1, false));

		compositeTitle = new Composite(compositeMain, SWT.NONE);
		GridLayout gl_compositeTitle = new GridLayout(1, false);
		gl_compositeTitle.marginWidth = 0;
		gl_compositeTitle.marginHeight = 0;
		compositeTitle.setLayout(gl_compositeTitle);
		GridData gd_compositeTitle = new GridData(SWT.FILL, SWT.CENTER, true, true, 1, 1);
		gd_compositeTitle.minimumWidth = 300;
		gd_compositeTitle.minimumHeight = 1;
		compositeTitle.setLayoutData(gd_compositeTitle);

		compositeAbout = new Composite(compositeMain, SWT.NONE);
		GridLayout gl_compositeAbout = new GridLayout(1, true);
		gl_compositeAbout.marginHeight = 0;
		gl_compositeAbout.marginWidth = 0;
		compositeAbout.setLayout(gl_compositeAbout);
		GridData gd_compositeAbout = new GridData(SWT.CENTER, SWT.CENTER, true, false, 1, 1);
		gd_compositeAbout.minimumWidth = 1;
		gd_compositeAbout.minimumHeight = 1;
		compositeAbout.setLayoutData(gd_compositeAbout);

		compositeInfo = new Composite(this, SWT.NONE);
		compositeInfo.setLayout(new GridLayout(2, false));
		FormData fd_compositeInfo = new FormData();
		fd_compositeInfo.right = new FormAttachment(100, 0);
		fd_compositeInfo.bottom = new FormAttachment(100, 0);
		compositeInfo.setLayoutData(fd_compositeInfo);

		compositeMonitor1 = new Composite(compositeInfo, SWT.NONE);
		GridData gd_compositeMonitor1 = new GridData(SWT.CENTER, SWT.CENTER, false, false, 1, 1);
		gd_compositeMonitor1.minimumWidth = 1;
		gd_compositeMonitor1.minimumHeight = 1;
		compositeMonitor1.setLayoutData(gd_compositeMonitor1);
		compositeMonitor2 = new Composite(compositeInfo, SWT.NONE);
		GridData gd_compositeMonitor2 = new GridData(SWT.CENTER, SWT.CENTER, false, false, 1, 1);
		gd_compositeMonitor2.minimumWidth = 1;
		gd_compositeMonitor2.minimumHeight = 1;
		compositeMonitor2.setLayoutData(gd_compositeMonitor2);
	}

	@Override
	protected void checkSubclass() {
		// Disable the check that prevents subclassing of SWT components
	}

	protected Composite getCompositeTitle() {
		return compositeTitle;
	}

	protected Composite getCompositeAbout() {
		return compositeAbout;
	}

	protected Composite getCompositeMonitor1() {
		return compositeMonitor1;
	}

	protected Composite getCompositeMonitor2() {
		return compositeMonitor2;
	}

	protected Composite getCompositeInfo() {
		return compositeInfo;
	}
}
