/**
 * This file is part of the TABuddy project.
 * Copyright (c) 2012-2013 Alexey Aksenov ezh@ezh.msk.ru
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Global License version 3
 * as published by the Free Software Foundation with the addition of the
 * following permission added to Section 15 as permitted in Section 7(a):
 * FOR ANY PART OF THE COVERED WORK IN WHICH THE COPYRIGHT IS OWNED
 * BY Limited Liability Company «MEZHGALAKTICHESKIJ TORGOVYJ ALIANS»,
 * Limited Liability Company «MEZHGALAKTICHESKIJ TORGOVYJ ALIANS» DISCLAIMS
 * THE WARRANTY OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Global License for more details.
 * You should have received a copy of the GNU Affero General Global License
 * along with this program; if not, see http://www.gnu.org/licenses or write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA, 02110-1301 USA, or download the license from the following URL:
 * http://www.gnu.org/licenses/agpl.html
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Global License.
 *
 * In accordance with Section 7(b) of the GNU Affero General Global License,
 * you must retain the producer line in every report, form or document
 * that is created or manipulated using TABuddy.
 *
 * You can be released from the requirements of the license by purchasing
 * a commercial license. Buying such a license is mandatory as soon as you
 * develop commercial activities involving the TABuddy software without
 * disclosing the source code of your own applications.
 * These activities include: offering paid services to customers,
 * serving files in a web or/and network application,
 * shipping TABuddy with a closed source product.
 *
 * For more information, please contact Digimead Team at this
 * address: ezh@ezh.msk.ru
 */

package org.digimead.tabuddy.desktop;

import java.lang.reflect.Field;

import org.eclipse.osgi.util.NLS;

/**
 * This file is autogenerated by Google WindowBuilder Pro
 *
 * @author ezh
 */
public class Messages extends NLS {
	private static final String BUNDLE_NAME = "org.digimead.tabuddy.desktop.messages"; //$NON-NLS-1$

	public static String acquire_text;
	public static String activate_text;
	public static String activeElement_text;
	public static String activeSchema_text;
	public static String active_text;
	public static String add_text;
	public static String additionalInformation_text;
	public static String alias_text;
	public static String argument_text;
	public static String ascending_text;
	public static String autoresize_key;
	public static String availability_text;
	public static String available_text;
	public static String base_text;
	public static String blocked_text;
	public static String cancelled_text;
	public static String closeFile_text;
	public static String collapseAll_text;
	public static String collapseRecursively_text;
	public static String console_text;
	public static String copy_item_text;
	public static String copy_text;
	public static String coreDiscover_text;
	public static String coreModel_text;
	public static String coreModel_tooltip_text;
	public static String coreSelected_text;
	public static String coreSelected_tooltip_text;
	public static String createFrom_text;
	public static String create_text;
	public static String cut_text;
	public static String default_text;
	public static String definition_text;
	public static String delete_text;
	public static String descending_text;
	public static String description_text;
	public static String direction_text;
	public static String down_text;
	public static String edit_text;
	public static String elementEditorDescription_text;
	public static String elementEditorDialog_text;
	public static String elementEditorTitle_text;
	public static String elementTemplateEditorDescription_text;
	public static String elementTemplateEditorDialog_text;
	public static String elementTemplateEditorTitle_text;
	public static String elementTemplateListDescription_text;
	public static String elementTemplateListDialog_text;
	public static String elementTemplateListTitle_text;
	public static String elementTemplates_text;
	public static String elementsPredefined_text;
	public static String emptyRows_text;
	public static String empty_text;
	public static String enumerationEditorDescription_text;
	public static String enumerationEditorDialog_text;
	public static String enumerationEditorTitle_text;
	public static String enumerationListDescription_text;
	public static String enumerationListDialog_text;
	public static String enumerationListTitle_text;
	public static String enumerationTooltip_text;
	public static String enumerationUnableToCreateNoTypes_text;
	public static String enumerationUnableToCreate_text;
	public static String enumerations_text;
	public static String errorReportContactHint_text;
	public static String errorReportContactTip_text;
	public static String errorReportContact_text;
	public static String errorReportDescription_text;
	public static String errorReportDetails_text;
	public static String errorReportReasonDefault_text;
	public static String errorReportTitle_text;
	public static String errorReportUploadAquireFailed_text;
	public static String errorReportUploadAquire_text;
	public static String errorReportUploadCancelled_text;
	public static String errorReportUploadFailed_text;
	public static String errorReportUploadTitle_text;
	public static String error_text;
	public static String exit_text;
	public static String expandAll_text;
	public static String expandNew_text;
	public static String expandRecursively_text;
	public static String expand_text;
	public static String field_text;
	public static String fields_text;
	public static String filter_text;
	public static String filters_text;
	public static String freeze_text;
	public static String group_text;
	public static String hidden_text;
	public static String hide_text;
	public static String identificatorCharacterIsNotValid_text;
	public static String identificatorIsAlreadyInUse_text;
	public static String identificatorIsNotDefined_text;
	public static String identificator_text;
	public static String identificators_text;
	public static String inversion_text;
	public static String key_text;
	public static String lastModification_text;
	public static String left_text;
	public static String link_text;
	public static String loadFile_text;
	public static String localModel_text;
	public static String localModel_tooltip_text;
	public static String localizedTypeSchemaDescription_text;
	public static String localizedTypeSchemaName_text;
	public static String lock_text;
	public static String lookupAliasInTranslations_text;
	public static String lookupFilter_text;
	public static String markAsRoot_text;
	public static String menuEdit_text;
	public static String menuFile_text;
	public static String menuModel_text;
	public static String nameIsAlreadyInUse_text;
	public static String nameIsNotDefined_text;
	public static String name_text;
	public static String newFilterName_text;
	public static String newSortingName_text;
	public static String newTypeSchema_text;
	public static String newValue_text;
	public static String newViewName_text;
	public static String new_text;
	public static String no_text;
	public static String nodata_text;
	public static String openFile_text;
	public static String paste_text;
	public static String path_text;
	public static String properties_text;
	public static String property_text;
	public static String reason_text;
	public static String redo_text;
	public static String remove_text;
	public static String required_text;
	public static String resetPredefinedTemplate_text;
	public static String resetSorting_text;
	public static String reset_text;
	public static String right_text;
	public static String rootElement_text;
	public static String saveFile_text;
	public static String select_text;
	public static String settings_text;
	public static String shell_detailed_text;
	public static String shell_text;
	public static String sorting_text;
	public static String sortings_text;
	public static String string_text;
	public static String synchronize_text;
	public static String systemElements_text;
	public static String tableView_text;
	public static String table_text;
	public static String thereAreDuplicatedValuesInField_text;
	public static String thereAreNoSelectedProperties_text;
	public static String thereIsNoData_text;
	public static String translationDialog_text;
	public static String tree_text;
	public static String typeEditorDescription_text;
	public static String typeEditorDialog_text;
	public static String typeEditorTitle_text;
	public static String typeInternalRepresentaion_text;
	public static String typeIsUnknown_text;
	public static String typeListDescription_text;
	public static String typeListDialog_text;
	public static String typeListTitle_text;
	public static String typeSchemaDefaultDescription_text;
	public static String typeSchemaPredefinedResetToDefault_text;
	public static String typeSchemaResetUnknownTypes_text;
	public static String typeSchemaTooltip_text;
	public static String typeSchemas_text;
	public static String type_text;
	public static String types_text;
	public static String undo_text;
	public static String unknown_view_text;
	public static String untitled_text;
	public static String up_text;
	public static String valueCharacterIsNotValid_text;
	public static String valueIsNotDefined_text;
	public static String value_text;
	public static String view_text;
	public static String view_tooltip_text;
	public static String views_text;
	public static String yes_text;
	public static String overViewPanelTitle_text;

	// //////////////////////////////////////////////////////////////////////////
	//
	// Class initialization
	//
	// //////////////////////////////////////////////////////////////////////////
	static {
		// load message values from bundle file
		NLS.initializeMessages(BUNDLE_NAME, Messages.class);
		final Field[] fieldArray = Messages.class.getDeclaredFields();
		final int len = fieldArray.length;
		for (int i = 0; i < len; i++) {
			final Field field = (Field) fieldArray[i];
			if (field.getType() == java.lang.String.class) {
				if (!field.isAccessible())
					field.setAccessible(true);
				try {
					final String rawValue = (String) field.get(null);
//					final String optValue = org.digimead.tabuddy.desktop.Resources$.MODULE$
//							.getMessage(Messages.class, field.getName());
//					if (optValue == null)
//						field.set(null,
//								new String(rawValue.getBytes("ISO-8859-1"),
//										"UTF-8").replaceAll("\\\\n", "\n")
//										.replaceAll("\\\\t", "\t"));
				} catch (Exception e) {
					// skip field modification
				}
			}
		}
//		org.digimead.tabuddy.desktop.Resources$.MODULE$
//				.registerMessages(Messages.class);
	}

	// //////////////////////////////////////////////////////////////////////////
	//
	// Constructor
	//
	// //////////////////////////////////////////////////////////////////////////
	private Messages() {
		// do not instantiate
	}
}
