/**
 * This file is part of the TABuddy project.
 * Copyright (c) 2012-2013 Alexey Aksenov ezh@ezh.msk.ru
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Global License version 3
 * as published by the Free Software Foundation with the addition of the
 * following permission added to Section 15 as permitted in Section 7(a):
 * FOR ANY PART OF THE COVERED WORK IN WHICH THE COPYRIGHT IS OWNED
 * BY Limited Liability Company «MEZHGALAKTICHESKIJ TORGOVYJ ALIANS»,
 * Limited Liability Company «MEZHGALAKTICHESKIJ TORGOVYJ ALIANS» DISCLAIMS
 * THE WARRANTY OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Global License for more details.
 * You should have received a copy of the GNU Affero General Global License
 * along with this program; if not, see http://www.gnu.org/licenses or write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA, 02110-1301 USA, or download the license from the following URL:
 * http://www.gnu.org/licenses/agpl.html
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Global License.
 *
 * In accordance with Section 7(b) of the GNU Affero General Global License,
 * you must retain the producer line in every report, form or document
 * that is created or manipulated using TABuddy.
 *
 * You can be released from the requirements of the license by purchasing
 * a commercial license. Buying such a license is mandatory as soon as you
 * develop commercial activities involving the TABuddy software without
 * disclosing the source code of your own applications.
 * These activities include: offering paid services to customers,
 * serving files in a web or/and network application,
 * shipping TABuddy with a closed source product.
 *
 * For more information, please contact Digimead Team at this
 * address: ezh@ezh.msk.ru
 */

package org.digimead.tabuddy.desktop.model.definition.dialog.eltemed;

import org.eclipse.jface.dialogs.IDialogConstants;
import org.eclipse.jface.dialogs.TitleAreaDialog;
import org.eclipse.jface.viewers.TableViewer;
import org.eclipse.jface.viewers.TableViewerColumn;
import org.eclipse.swt.SWT;
import org.eclipse.swt.layout.GridData;
import org.eclipse.swt.layout.GridLayout;
import org.eclipse.swt.widgets.Composite;
import org.eclipse.swt.widgets.Control;
import org.eclipse.swt.widgets.Label;
import org.eclipse.swt.widgets.Shell;
import org.eclipse.swt.widgets.Table;
import org.eclipse.swt.widgets.TableColumn;
import org.eclipse.swt.widgets.Text;

import swing2swt.layout.BorderLayout;
import swing2swt.layout.FlowLayout;
import org.eclipse.swt.widgets.Button;

/**
 * This file is autogenerated by Google WindowBuilder Pro
 *
 * @author ezh
 */
public class ElementTemplateEditorSkel extends TitleAreaDialog {
	private Button btnCheckAvailability;
	private Composite compositeFooter;
	private Composite compositeHeader;
	private TableViewer tableViewer;
	private TableViewerColumn tableViewerColumnDefault;
	private TableViewerColumn tableViewerColumnGroup;
	private TableViewerColumn tableViewerColumnId;
	private TableViewerColumn tableViewerColumnRequired;
	private TableViewerColumn tableViewerColumnType;
	private Text textTemplateId;
	private Text textTemplateName;

	/**
	 * Create the dialog.
	 *
	 * @param parentShell
	 */
	public ElementTemplateEditorSkel(Shell parentShell) {
		super(parentShell);
		setShellStyle(SWT.DIALOG_TRIM | SWT.RESIZE | SWT.PRIMARY_MODAL);
	}

	/**
	 * Create contents of the dialog.
	 *
	 * @param parent
	 */
	@Override
	protected Control createDialogArea(Composite parent) {
		setMessage(org.digimead.tabuddy.desktop.Messages$.MODULE$.elementTemplateEditorDescription_text());
		setTitle(org.digimead.tabuddy.desktop.Messages$.MODULE$.elementTemplateEditorTitle_text());
		Composite area = (Composite) super.createDialogArea(parent);
		Composite container = new Composite(area, SWT.NONE);
		container.setLayout(new BorderLayout(0, 0));
		container.setLayoutData(new GridData(GridData.FILL_BOTH));

		compositeHeader = new Composite(container, SWT.NONE);
		compositeHeader.setLayoutData(BorderLayout.NORTH);
		compositeHeader.setLayout(new GridLayout(2, false));

		Label lblTemplateId = new Label(compositeHeader, SWT.NONE);
		lblTemplateId.setAlignment(SWT.RIGHT);
		lblTemplateId.setLayoutData(new GridData(SWT.RIGHT, SWT.CENTER,
				false, false, 1, 1));
		lblTemplateId.setBounds(0, 0, 65, 15);
		lblTemplateId.setText(org.digimead.tabuddy.desktop.Messages$.MODULE$.identificator_text());

		textTemplateId = new Text(compositeHeader, SWT.BORDER);
		textTemplateId.setLayoutData(new GridData(SWT.FILL, SWT.CENTER, true,
				false, 1, 1));
		textTemplateId.setText("");

		Label lblTemplateName = new Label(compositeHeader, SWT.NONE);
		lblTemplateName.setAlignment(SWT.RIGHT);
		lblTemplateName.setLayoutData(new GridData(SWT.RIGHT, SWT.CENTER, false,
				false, 1, 1));
		lblTemplateName.setText(org.digimead.tabuddy.desktop.Messages$.MODULE$.name_text());

		textTemplateName = new Text(compositeHeader, SWT.BORDER);
		textTemplateName.setLayoutData(new GridData(SWT.FILL,
				SWT.CENTER, true, false, 1, 1));
		textTemplateName.setText("");
		new Label(compositeHeader, SWT.NONE);

		btnCheckAvailability = new Button(compositeHeader, SWT.CHECK);
		btnCheckAvailability.setText(org.digimead.tabuddy.desktop.Messages$.MODULE$.availability_text());

		tableViewer = new TableViewer(container, SWT.BORDER
				| SWT.FULL_SELECTION);
		Table table = tableViewer.getTable();
		table.setLinesVisible(true);
		table.setHeaderVisible(true);

		tableViewerColumnId = new TableViewerColumn(tableViewer, SWT.NONE);
		TableColumn tblclmnId = tableViewerColumnId.getColumn();
		tblclmnId.setWidth(100);
		tblclmnId.setText(org.digimead.tabuddy.desktop.Messages$.MODULE$.property_text());

		tableViewerColumnRequired = new TableViewerColumn(tableViewer, SWT.NONE);
		TableColumn tblclmnRequired = tableViewerColumnRequired.getColumn();
		tblclmnRequired.setWidth(100);
		tblclmnRequired.setText(org.digimead.tabuddy.desktop.Messages$.MODULE$.required_text());

		tableViewerColumnType = new TableViewerColumn(tableViewer, SWT.NONE);
		TableColumn tblclmnType = tableViewerColumnType.getColumn();
		tblclmnType.setWidth(100);
		tblclmnType.setText(org.digimead.tabuddy.desktop.Messages$.MODULE$.type_text());

		tableViewerColumnDefault = new TableViewerColumn(tableViewer, SWT.NONE);
		TableColumn tblclmnDefault = tableViewerColumnDefault.getColumn();
		tblclmnDefault.setWidth(100);
		tblclmnDefault.setText(org.digimead.tabuddy.desktop.Messages$.MODULE$.default_text());

		tableViewerColumnGroup = new TableViewerColumn(tableViewer, SWT.NONE);
		TableColumn tblclmnGroup = tableViewerColumnGroup.getColumn();
		tblclmnGroup.setWidth(100);
		tblclmnGroup.setText(org.digimead.tabuddy.desktop.Messages$.MODULE$.group_text());

		compositeFooter = new Composite(container, SWT.NONE);
		compositeFooter.setLayoutData(BorderLayout.SOUTH);
		compositeFooter.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));

		return area;
	}

	/**
	 * Create contents of the button bar.
	 *
	 * @param parent
	 */
	@Override
	protected void createButtonsForButtonBar(Composite parent) {
		Button button = createButton(parent, IDialogConstants.OK_ID, IDialogConstants.OK_LABEL,
				true);
		button.setEnabled(false);
		createButton(parent, IDialogConstants.CANCEL_ID,
				IDialogConstants.CANCEL_LABEL, false);
	}

	protected Composite getCompositeFooter() {
		return compositeFooter;
	}

	protected TableViewer getTableViewer() {
		return tableViewer;
	}

	protected Text getTextTemplateName() {
		return textTemplateName;
	}

	protected Text getTextTemplateId() {
		return textTemplateId;
	}

	protected Button getBtnCheckAvailability() {
		return btnCheckAvailability;
	}

	protected TableViewerColumn getTableViewerColumnId() {
		return tableViewerColumnId;
	}

	protected TableViewerColumn getTableViewerColumnRequired() {
		return tableViewerColumnRequired;
	}

	protected TableViewerColumn getTableViewerColumnType() {
		return tableViewerColumnType;
	}

	protected TableViewerColumn getTableViewerColumnDefault() {
		return tableViewerColumnDefault;
	}

	protected TableViewerColumn getTableViewerColumnGroup() {
		return tableViewerColumnGroup;
	}
}
